import rest1 from "../public/images/rest1.avif"
import rest2 from "../public/images/rest2.avif"
import rest3 from "../public/images/rest3.avif"
import rest4 from "../public/images/rest4.avif"
import rest5 from "../public/images/rest5.avif"
import rest6 from "../public/images/rest6.avif"
import rest7 from "../public/images/rest7.avif"
import rest8 from "../public/images/rest8.avif"
import rest9 from "../public/images/rest9.avif"
import rest10 from "../public/images/rest10.avif"
import rest11 from "../public/images/rest11.avif"
import rest12 from "../public/images/rest12.avif"
import rest13 from "../public/images/rest13.avif"
import rest14 from "../public/images/rest14.avif"
import rest15 from "../public/images/rest15.avif"
import rest16 from "../public/images/rest16.avif"
import rest17 from "../public/images/rest17.avif"
import rest18 from "../public/images/rest18.avif"
import rest19 from "../public/images/rest19.avif"
import rest20 from "../public/images/rest20.avif"

export const RestData = [
    {
        img: rest1,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest2,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.8",
        minTime: "30",
        maxTime: "40",
        name: "Ice Cream Desserts",
        place: "Hatia",
    },
    {
        img: rest3,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.3",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Lalpur",
    },
    {
        img: rest4,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest5,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest6,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest7,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest8,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest9,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest10,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest11,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest12,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest13,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest14,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest15,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest16,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest17,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest18,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest19,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
    {
        img: rest20,
        offer: "Items at ₹179",
        title: "Pizza Hut",
        rating: "4.2",
        minTime: "30",
        maxTime: "40",
        name: "Pizzas",
        place: "Ashok Nagar",
    },
]